# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publication"
  weight = 40

#[[main]]
#  name = "Gallery"
#  url = "#gallery"
#  weight = 50
#
#[[main]]
#  name = "Guang Zhou"
#  url = "/gallery/guangzhou/content"
#  parent = "Photo Gallery"
#
#[[main]]
#  name = "Japan"
#  url = "#japan"
#  parent = "Photo Gallery"
#
#[[main]]
#  name = "Turkey"
#  url = "#turkey"
#  parent = "Photo Gallery"
#
#[[main]]
#  name = "Xinjiang"
#  url = "#xinjiang"
#  parent = "Photo Gallery"
#
#
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
